# Translations template for vigilo-vigiconf-local.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the vigilo-vigiconf-local
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: vigilo-vigiconf-local 2.0.16\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2012-07-18 17:58+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/vigiconf_local/__init__.py:46
msgid "%prog [options] command [arguments]"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:48
msgid "Only print the command that would be run"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:51
#, python-format
msgid "No command selected. Available commands: %s"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:56
#, python-format
msgid "Unknown command. Available commands: %s"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:70
#, python-format
msgid "Wrong number of arguments. Expected: %s"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:81
#, python-format
msgid "Setup error: %s"
msgstr ""

#: src/vigilo/vigiconf_local/__init__.py:84
#, python-format
msgid "Error: %s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:111
#, python-format
msgid "The archive '%s' does not exist, copy it first"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:130
#, python-format
msgid "Can't untar the configuration: %(output)s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:172
msgid "Please specify an application name to validate"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:175
#, python-format
msgid "No validation script: %s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:192
#, python-format
msgid "Validation failed for application '%(app)s'. Output: %(output)s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:214
msgid "The 'new' directory does not exist. Deploy the configuration first."
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:221
msgid "Backing up the directory 'prod' to 'old', and renaming 'new' into 'prod'"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:237
#, python-format
msgid ""
"Configuration activation failed: %(error)s. User '%(user)s' must have write "
"access to '%(dir)s'."
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:245
#, python-format
msgid "Configuration activation failed: %s."
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:269
#, python-format
msgid "The script '%(script)s' does not exist for application '%(app)s'"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:288
#, python-format
msgid ""
"Action %(action)s failed for application %(app)s. Code: %(code)d. Output: "
"%(output)s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:335
#, python-format
msgid "The directory '%s' does not exist."
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:341
#, python-format
msgid "Getting revisions from these directories: %s"
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:375
msgid "The directory 'new' does not exist."
msgstr ""

#: src/vigilo/vigiconf_local/commands.py:381
#, python-format
msgid "Setting revision to: %s"
msgstr ""

